name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: beta
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: deploy to beta
        run: earthly --secret FLY_API_TOKEN +deploy.backend --stage=beta
